### ISSUE TITLE
Error quan es crea una sol·licitud d'anàlisi utilitzant un contenidor que té accents

### ISSUE THREAD

**Issue by xispa** [institutmontilivi/Bika-LIMS#19]
Si s'intenta crear una sol·licitud d'anàlisi seleccionant un contenidor amb accents, dóna error

**Comment by Espurna** [comment]
No puc reproduir el problema, utilitzo (en la creacií de l'AR) un contenidor "Ampolla Plàstic" i puc seguir tot el flux de treball de la sol·licitud fins a la seva publicació.
