### ISSUE TITLE
Nom de client en blanc a llista de sol·licituds d'anàlisi

### ISSUE THREAD

**Issue by xispa** [institutmontilivi/Bika-LIMS#25]
A les taules de sol·licitud d'anàlisi, en alguns casos, el camp de client apareix en blanc:

![captura](https://f.cloud.github.com/assets/832627/1326702/b5f9b73c-34e3-11e3-9f2a-fd857853bad6.png)

**Comment by martacosvi** [comment]
Comprovat. De totes maneres, entro un nou Issue perquè passa el mateix a la llista de Mostres
