### ISSUE TITLE
Error en crear una sol·licitud d'anàlisi si la capacitat del contenidor i unitats estan juntes

### ISSUE THREAD

**Issue by xispa** [institutmontilivi/Bika-LIMS#26]
Si les unitats de mesura i la capacitat d'un contenidor no estan separades per un espai en blanc (per exemple '1000ml' en comptes de '1000 ml', la creació d'una sol·licitud d'anàlisi dóna error:

```
ERROR Zope.SiteErrorLog 1381764676.220.695926928451 http://localhost:8080/Plone/clients/client-2/analysisrequest_submit
Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module bika.lims.browser.analysisrequest, line 1729, in __call__
  Module bika.lims.browser.analysisrequest, line 1734, in <lambda>
ValueError: invalid literal for float(): 1000ml
```

**Comment by martacosvi** [comment]
No ho puc comprovar: en fer la sol·licitud em demana el Tipus de contenidor (p.e. Ampolla plàstic) no el Contenidor concret (Ampolla plàstic 500 mL). En definir el tipus de contenidor no s'especifica la corresponent capacitat
