### ISSUE TITLE
Dades d'accés no apareix a l'usuari client

### ISSUE THREAD

**Issue by martacosvi** [institutmontilivi/Bika-LIMS#27]
He creat un accés per a un client extern (usuari: client; contrassenya: client13). Tot i que m'ha arribat un correu per a canviar la contrassenya,  quan accedeixo al lims veig que no està habilitada la pestanya de Dades d'accés per al propi usuari de manera que l'usuari es pugui canviar la contrassenya en qualsevol moment.

**Comment by xispa** [comment]
En entrar amb aquestes credencials, si fa clic sobre el menú superior de l'extrem dret i que porta el seu nom (en aquest cas, 'client') i després fa clic sobre 'Preferències' es mostra la vista del client.En aquesta vista, per defecte es mostra la pestanya 'Preferències personals', però hi ha una altra pestanya 'Contrasenya' al costat des d'on pot canviar-la.
