### ISSUE TITLE
L'analista no té privilegis suficients per afegir fitxers adjunts a WS

### ISSUE THREAD

**Issue by martacosvi** [institutmontilivi/Bika-LIMS#29]
L'analista no té suficients permisos per adjuntar un fitxer en el WS, només ho pot fer LabManager. Crec que l'analista també ho hauria de poder fer.

**Comment by xispa** [comment]
Nota mental: el privilegi 'Add Attachment' no existeix. Se suposa que els usuaris 'Authenticated' haurien de poder donar d'alta items per al tipus Attachment, però no és així. Cal revisar el workflow 'worksheet_workflow' quan estat és 'open'.
