### ISSUE TITLE
INSTRUMENT TYPES arxiu de dades-LIMS

### ISSUE THREAD

**Issue by martacosvi** [institutmontilivi/Bika-LIMS#46]
Un cop carregat l'arxiu de dades al LIMS. Tot i que hi ha informació a la pestanya INSTRUMENT TYPES dels full de dades, en el LIMS no apareix aquesta info. De la mateixa manera a la pestanya EQUIPS de la fulla de dades, hi ha especificat el tipus d'instrument de cada equip, però això no queda reflexat en el LIMS

**Comment by Espurna** [comment]
No hi ha manera de trobar l'error, em sap greu... 

Ara per ara pots utilitzar aquest "truc":

Encara que no es mostren els InstrumentTypes a la llista, en realitat si que existeixen, pots accedir al primer instrument type amb la url: 
~/Plone/bika_setup/bika_instrumenttypes/instrumenttype-1

Al segon amb la url acabada en ~/instrumenttype-2 i així successivament.
Un cop et trobis dins la pàgina d'edició de l'instrument type, si apretes "save", veuràs que t'apereixerà l'instrument type a la llista.

**Comment by martacosvi** [comment]
Em sap greu però no entenc els "trucs". Amb quina pàgina haig de fer la cerca amb aquest url? On de la pàgina?
