### ISSUE TITLE
REFERENCE DEFINITIONS

### ISSUE THREAD

**Issue by martacosvi** [institutmontilivi/Bika-LIMS#47]
Comentari del Full de dades a carregar. En la pestanya de REFERENCE DEFINITIONS del full de dades apareixen les columnes "Data creació" i "Data caducitat". En el LIMS, no apareixen aquí sinó a la pestanya "Mostres de referència" o "Reference samples". 
Crec que s'haurien d'eliminar d'aquesta pestanya de la fulla de dades i afegir una nova pestanya (en la fulla de dades no hi ha la pestanya "Reference Samples")

**Comment by xispa** [comment]
Reference Definitions i Reference Samples són conceptes diferents. Les Reference Definitions serveixen per crear unes especificacions concretes que després puguin ser assignades a mostres de referència (Reference Samples) concretes. 

No hi ha fulla de Reference Samples pel mateix motiu que no hi ha fulla de solicituds d'anàlisi o mostres... cada Reference Sample correspon a un 'flascó' concret de mostra patró/blanc d'un proveïdor concret amb una data i lot concrets. Els Reference Sample sempre s'han de crear manualment.
