### ISSUE TITLE
Full de dades: CONSTANTS

### ISSUE THREAD

**Issue by martacosvi** [institutmontilivi/Bika-LIMS#48]
Modificació realitzada en el full de dades a carregar. En la darrera pestanya de la fulla, hi he canviat el rol/grup d'analistes tinguin opció de fer attachments (Columna D Permitted). Potser així ara l'analista sí podrà adjuntar arxius a un WS?

**Comment by xispa** [comment]
No ho tinc clar, s'hauria de provar

**Comment by Espurna** [comment]
Crec que això ho vam resoldre...

https://github.com/institutmontilivi/Bika-LIMS/commit/5e6f52199fc6122e62217f77fbdc233489f41fe0#diff-220f998dab47de85deab1e34b5713328R25

**Comment by martacosvi** [comment]
Efectivament, sense haver carregat l'excel on hi ha el canvi, ja funciona (analistes poden fer attachments). És a dir que torno a treure la opció de l'excel.
