### ISSUE TITLE
Attachment type full de dades

### ISSUE THREAD

**Issue by martacosvi** [institutmontilivi/Bika-LIMS#49]
Cal afegir aquesta pestanya al full de dades, per tal que es puguin fer attachments després de la càrrega de l'arxiu al sistema. 
Entrar-ne almenys un tipus:
TÍTOL: Fotografies microscopi
DESCRIPCIÓ: Imatges obtingudes al microscopi òptic (x100)

**Comment by Espurna** [comment]
He enviat un correu on hi ha la fulla d'attachment type amb l'exemple del microscopi que has dit.

**Comment by martacosvi** [comment]
Carregat l'arxiu de dades i ha funcionat correctament: s'ha creat el tipus d'attacment directament
