### ISSUE TITLE
Error en publicar resultats

### ISSUE THREAD

**Issue by martacosvi** [institutmontilivi/Bika-LIMS#50]
Ho sentim, sembla que hi ha un error…
Aquest és el missatge d'error complet:

Error sorgit en publicar un informe de resultats "estàndard": sense adjunts ni càlculs extres

Traceback (innermost last):

Module ZPublisher.Publish, line 126, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 46, in call_object
Module bika.lims.browser.client, line 219, in **call**
Module bika.lims.browser.publish, line 177, in **call**
Module Products.MailHost.MailHost, line 237, in send
Module Products.MailHost.MailHost, line 337, in _send
Module Products.CMFPlone.patches.sendmail, line 12, in _catch
Module zope.sendmail.mailer, line 77, in send
Module smtplib, line 734, in sendmail
Module smtplib, line 495, in data
SMTPDataError: (421, '4.7.0 Temporary System Problem. Try again later (WS). fa7sm22068136wjd.27 - gsmtp')

**Comment by martacosvi** [comment]
Han canviat a principi de curs algun aspecte de configuració de xarxa a l'institut? Consultar amb Imma Moreno

**Comment by xispa** [comment]
Efectivament, aquest error té lloc quan hi ha un problema de connexió amb el servidor de correu SMTP. El LIMS utilitza gmail (servidor smtp.gmail.com) per enviar els correus electrònics. Potser han canviat la configuració de la xarxa de l'institut per evitar l'accés a Gmail. Cal assegurar que el servidor on hi ha el LIMS no tingui l'accés capat a gmail.

**Comment by martacosvi** [comment]
S'ha revisat la configuració del correu, s'havia desconfigurat (sol??). Arreglat
