### ISSUE TITLE
Nom de client en blanc la llista de Mostres

### ISSUE THREAD

**Issue by martacosvi** [institutmontilivi/Bika-LIMS#51]
![nom client](https://cloud.githubusercontent.com/assets/5686107/4550195/935e7b04-4e64-11e4-8ab4-bba081c86c9e.png)

**Comment by Espurna** [comment]
Com pots observar, a mi em funciona correctament. He fet una Solicitud d'anàlisi normal i corrent, com ho has fet tu?

![sample_client](https://cloud.githubusercontent.com/assets/7425587/4558210/183f60f4-4edd-11e4-9116-745c71643a68.png)

**Comment by martacosvi** [comment]
Jo continuo sense visualitzar aquest camp (m'apareix la columna en blanc). També fent Sol·licituds normal i corrent...
